spring.application.name=project-management
spring.datasource.url=jdbc:postgresql://localhost:5432/project_tracker_db
spring.datasource.username=postgres
spring.datasource.password=Menaka@2006

#to update table automatically
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

server.port=8080

# JWT Configuration
jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
jwt.expiration=86400000

# CORS
cors.allowed.origins=http://localhost:3000

spring.main.allow-bean-definition-overriding=true 


